service: backend

provider:
  name: aws
  runtime: nodejs12.x

functions:
  create:
    handler: handler.create # point to exported create function in handler.js
    events:
      - http:
          path: leads # path will be domain.name.com/dev/leads
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: leads/{id} # path will be domain.name.com/dev/leads/1
          method: get
          cors: true
  getAll:
    handler: handler.getAll # path will be domain.name.com/dev/leads
    events:
      - http:
          path: leads
          method: get
          cors: true
  update:
    handler: handler.update # path will be domain.name.com/dev/leads/1
    events:
      - http:
          path: leads/{id}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: leads/{id} # path will be domain.name.com/dev/leads/1
          method: delete
          cors: true
